name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  # مكتبات فايربيز الأساسية
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.7.0
  permission_handler: ^12.0.1
  camera: ^0.12.0+1
  flutter_tts: ^4.2.5
  google_generative_ai: ^0.4.7
firebase_auth: ^5.1.2
firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true